#!/bin/sh

# map aliases from git to bash
# foreach git alias 'x', create bash alias 'gx'
eval $(git config --get-regexp '^alias\.[^ ]+' | \
	sed -e 's/^alias\.\([^ ]*\) \([^ !]\+\)\(.*\)$/alias g\1="git \1";/' \
	    -e 's/^alias\.\([^ ]*\) \!\(.*\)$/alias g\1="\2";/')

alias l='ls'
alias la='ls -A'
alias ll='ls -lF'
alias lla='ls -lAF'
alias lal='ls -lAF'

alias c='cd'
alias ...='cd ..; ls'
alias ....='cd ../..; ls'
alias .....='cd ../../..; ls'
